# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings !!!!! NOTICE THIS IS ALL THE SITE STUFF GOES
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jekyll for Web Designers
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a website I'm making to learn how to create websties from scratch.
baseurl: "/jekyll-for-designers" # the subpath of your site, e.g. /blog
# https or http?
url: "https://arthurjl.github.io/jekyll-for-designers" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll
tagline: "A basic guide to Jekyll"

# Build settings
markdown: kramdown
kramdown: 
  auto_ids: false
theme: minima
plugins:
  - jekyll-feed
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
